name: Build with ko

on:
  workflow_call: 
    inputs:
      private_repos:
        description: 'GOPRIVATE environment variable'
        required: false
        type: string
      cgo_enabled:
        description: 'Enable CGO for the build (1=enabled, 0=disabled)'
        required: false
        default: '0'
        type: string
    secrets:    
      GH_ACCESS_TOKEN:
        description: 'PAT for private Go modules'
        required: false

jobs:
  ko-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Go mod cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
            
      - uses: ko-build/setup-ko@v0.9
      
      - name: Generate version with semver.sh
        id: semver
        run: |
          VERSION=$(curl -sSL "https://raw.githubusercontent.com/metraction/github-actions/refs/heads/incremental/scripts/semver.sh" | bash)
          VERSION=$(echo $VERSION | sed 's/+/_/g')

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version: $VERSION"
          
      - name: Configure Go for private repos
        run: |
          if [ -n "${{ inputs.private_repos }}" ]; then
            echo "GOPRIVATE=${{ inputs.private_repos }}" >> $GITHUB_ENV
            git config --global url."https://${{ secrets.GH_ACCESS_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          fi
      
      - name: Build image with ko
        env:
          CGO_ENABLED: ${{ inputs.cgo_enabled }}
        run: |
          ko build --sbom=none --platform=linux/amd64 --bare --tags=$VERSION --image-label="repo_url=${{ github.event.repository.html_url }},commit_sha=${{ github.sha }}"
